create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 axi_bram_X0
set_property -dict [list CONFIG.PROTOCOL {AXI4LITE} CONFIG.SINGLE_PORT_BRAM {1} CONFIG.ECC_TYPE {0}] [get_bd_cells axi_bram_X0]

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 axi_bram_X1
set_property -dict [list CONFIG.PROTOCOL {AXI4LITE} CONFIG.SINGLE_PORT_BRAM {1} CONFIG.ECC_TYPE {0}] [get_bd_cells axi_bram_X1]

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 axi_bram_Y
set_property -dict [list CONFIG.PROTOCOL {AXI4LITE} CONFIG.SINGLE_PORT_BRAM {1} CONFIG.ECC_TYPE {0}] [get_bd_cells axi_bram_Y]


# From AXI Input -> Neural Network
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_00] [get_bd_pins neural_net_double_da_0/W1_00]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_01] [get_bd_pins neural_net_double_da_0/W1_01]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_10] [get_bd_pins neural_net_double_da_0/W1_10]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_11] [get_bd_pins neural_net_double_da_0/W1_11]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_20] [get_bd_pins neural_net_double_da_0/W1_20]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_21] [get_bd_pins neural_net_double_da_0/W1_21]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_30] [get_bd_pins neural_net_double_da_0/W1_30]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_31] [get_bd_pins neural_net_double_da_0/W1_31]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_40] [get_bd_pins neural_net_double_da_0/W1_40]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W1_41] [get_bd_pins neural_net_double_da_0/W1_41]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_00] [get_bd_pins neural_net_double_da_0/W2_00]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_01] [get_bd_pins neural_net_double_da_0/W2_01]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_02] [get_bd_pins neural_net_double_da_0/W2_02]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_03] [get_bd_pins neural_net_double_da_0/W2_03]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_04] [get_bd_pins neural_net_double_da_0/W2_04]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_10] [get_bd_pins neural_net_double_da_0/W2_10]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_11] [get_bd_pins neural_net_double_da_0/W2_11]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_12] [get_bd_pins neural_net_double_da_0/W2_12]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_13] [get_bd_pins neural_net_double_da_0/W2_13]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_14] [get_bd_pins neural_net_double_da_0/W2_14]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_20] [get_bd_pins neural_net_double_da_0/W2_20]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_21] [get_bd_pins neural_net_double_da_0/W2_21]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_22] [get_bd_pins neural_net_double_da_0/W2_22]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_23] [get_bd_pins neural_net_double_da_0/W2_23]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_24] [get_bd_pins neural_net_double_da_0/W2_24]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_30] [get_bd_pins neural_net_double_da_0/W2_30]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_31] [get_bd_pins neural_net_double_da_0/W2_31]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_32] [get_bd_pins neural_net_double_da_0/W2_32]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_33] [get_bd_pins neural_net_double_da_0/W2_33]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_34] [get_bd_pins neural_net_double_da_0/W2_34]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_40] [get_bd_pins neural_net_double_da_0/W2_40]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_41] [get_bd_pins neural_net_double_da_0/W2_41]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_42] [get_bd_pins neural_net_double_da_0/W2_42]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_43] [get_bd_pins neural_net_double_da_0/W2_43]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W2_44] [get_bd_pins neural_net_double_da_0/W2_44]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W3_00] [get_bd_pins neural_net_double_da_0/W3_00]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W3_01] [get_bd_pins neural_net_double_da_0/W3_01]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W3_02] [get_bd_pins neural_net_double_da_0/W3_02]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W3_03] [get_bd_pins neural_net_double_da_0/W3_03]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/W3_04] [get_bd_pins neural_net_double_da_0/W3_04]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b1_00] [get_bd_pins neural_net_double_da_0/b1_00]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b1_10] [get_bd_pins neural_net_double_da_0/b1_10]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b1_20] [get_bd_pins neural_net_double_da_0/b1_20]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b1_30] [get_bd_pins neural_net_double_da_0/b1_30]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b1_40] [get_bd_pins neural_net_double_da_0/b1_40]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b2_00] [get_bd_pins neural_net_double_da_0/b2_00]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b2_10] [get_bd_pins neural_net_double_da_0/b2_10]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b2_20] [get_bd_pins neural_net_double_da_0/b2_20]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b2_30] [get_bd_pins neural_net_double_da_0/b2_30]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b2_40] [get_bd_pins neural_net_double_da_0/b2_40]
connect_bd_net [get_bd_pins AXI_neural_input_int_0/b3_00] [get_bd_pins neural_net_double_da_0/b3_00]

# Fron Neural Network -> AXI Output
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_00_out] [get_bd_pins AXI_neural_output_in_0/W1_00]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_01_out] [get_bd_pins AXI_neural_output_in_0/W1_01]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_10_out] [get_bd_pins AXI_neural_output_in_0/W1_10]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_11_out] [get_bd_pins AXI_neural_output_in_0/W1_11]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_20_out] [get_bd_pins AXI_neural_output_in_0/W1_20]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_21_out] [get_bd_pins AXI_neural_output_in_0/W1_21]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_30_out] [get_bd_pins AXI_neural_output_in_0/W1_30]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_31_out] [get_bd_pins AXI_neural_output_in_0/W1_31]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_40_out] [get_bd_pins AXI_neural_output_in_0/W1_40]
connect_bd_net [get_bd_pins neural_net_double_da_0/W1_41_out] [get_bd_pins AXI_neural_output_in_0/W1_41]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_00_out] [get_bd_pins AXI_neural_output_in_0/W2_00]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_01_out] [get_bd_pins AXI_neural_output_in_0/W2_01]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_02_out] [get_bd_pins AXI_neural_output_in_0/W2_02]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_03_out] [get_bd_pins AXI_neural_output_in_0/W2_03]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_04_out] [get_bd_pins AXI_neural_output_in_0/W2_04]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_10_out] [get_bd_pins AXI_neural_output_in_0/W2_10]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_11_out] [get_bd_pins AXI_neural_output_in_0/W2_11]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_12_out] [get_bd_pins AXI_neural_output_in_0/W2_12]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_13_out] [get_bd_pins AXI_neural_output_in_0/W2_13]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_14_out] [get_bd_pins AXI_neural_output_in_0/W2_14]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_20_out] [get_bd_pins AXI_neural_output_in_0/W2_20]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_21_out] [get_bd_pins AXI_neural_output_in_0/W2_21]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_22_out] [get_bd_pins AXI_neural_output_in_0/W2_22]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_23_out] [get_bd_pins AXI_neural_output_in_0/W2_23]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_24_out] [get_bd_pins AXI_neural_output_in_0/W2_24]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_30_out] [get_bd_pins AXI_neural_output_in_0/W2_30]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_31_out] [get_bd_pins AXI_neural_output_in_0/W2_31]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_32_out] [get_bd_pins AXI_neural_output_in_0/W2_32]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_33_out] [get_bd_pins AXI_neural_output_in_0/W2_33]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_34_out] [get_bd_pins AXI_neural_output_in_0/W2_34]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_40_out] [get_bd_pins AXI_neural_output_in_0/W2_40]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_41_out] [get_bd_pins AXI_neural_output_in_0/W2_41]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_42_out] [get_bd_pins AXI_neural_output_in_0/W2_42]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_43_out] [get_bd_pins AXI_neural_output_in_0/W2_43]
connect_bd_net [get_bd_pins neural_net_double_da_0/W2_44_out] [get_bd_pins AXI_neural_output_in_0/W2_44]
connect_bd_net [get_bd_pins neural_net_double_da_0/W3_00_out] [get_bd_pins AXI_neural_output_in_0/W3_00]
connect_bd_net [get_bd_pins neural_net_double_da_0/W3_01_out] [get_bd_pins AXI_neural_output_in_0/W3_01]
connect_bd_net [get_bd_pins neural_net_double_da_0/W3_02_out] [get_bd_pins AXI_neural_output_in_0/W3_02]
connect_bd_net [get_bd_pins neural_net_double_da_0/W3_03_out] [get_bd_pins AXI_neural_output_in_0/W3_03]
connect_bd_net [get_bd_pins neural_net_double_da_0/W3_04_out] [get_bd_pins AXI_neural_output_in_0/W3_04]
connect_bd_net [get_bd_pins neural_net_double_da_0/b1_00_out] [get_bd_pins AXI_neural_output_in_0/b1_00]
connect_bd_net [get_bd_pins neural_net_double_da_0/b1_10_out] [get_bd_pins AXI_neural_output_in_0/b1_10]
connect_bd_net [get_bd_pins neural_net_double_da_0/b1_20_out] [get_bd_pins AXI_neural_output_in_0/b1_20]
connect_bd_net [get_bd_pins neural_net_double_da_0/b1_30_out] [get_bd_pins AXI_neural_output_in_0/b1_30]
connect_bd_net [get_bd_pins neural_net_double_da_0/b1_40_out] [get_bd_pins AXI_neural_output_in_0/b1_40]
connect_bd_net [get_bd_pins neural_net_double_da_0/b2_00_out] [get_bd_pins AXI_neural_output_in_0/b2_00]
connect_bd_net [get_bd_pins neural_net_double_da_0/b2_10_out] [get_bd_pins AXI_neural_output_in_0/b2_10]
connect_bd_net [get_bd_pins neural_net_double_da_0/b2_20_out] [get_bd_pins AXI_neural_output_in_0/b2_20]
connect_bd_net [get_bd_pins neural_net_double_da_0/b2_30_out] [get_bd_pins AXI_neural_output_in_0/b2_30]
connect_bd_net [get_bd_pins neural_net_double_da_0/b2_40_out] [get_bd_pins AXI_neural_output_in_0/b2_40]
connect_bd_net [get_bd_pins neural_net_double_da_0/b3_00_out] [get_bd_pins AXI_neural_output_in_0/b3_00]
